### ISSUE TITLE
TypeError: __webpack_modules__[moduleId].call is not a function

### ISSUE THREAD

**Issue by eugenet8k** [Trias/debug-names-webpack-plugin#1]
I have a fairly big application with a few chunks loaded per request (not included in the main application file). I have this error when I start application:

```
Uncaught (in promise) TypeError: __webpack_modules__[moduleId].call is not a function
    at __webpack_require__ (application.js:31595:42)
```

```js
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
...
/******/ 		// Execute the module function           THIS LINE FAILS 
/******/ 		__webpack_modules__[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

I looked into `__webpack_modules__` map and see that some of the entries are just `false`.

I can't say in what way those modules are different from others that have a function value in that map.

**Comment by Trias** [comment]
Hi eugenet8k!

thanks for trying the plugin. It‘s still very rough, so some issues are expected.

which version of webpack are you using, and which settings (could you maybe share your webpack.config.js?

can you reproduce the issue with a minimal setup?

**Comment by eugenet8k** [comment]
@Trias it is

```
    "webpack": "5.65.0",
    "webpack-cli": "4.9.1",
    "webpack-config-utils": "2.3.1",
    "webpack-dev-server": "4.7.2",
    "webpack-node-externals": "3.0.0",
    "webpack-stats-plugin": "1.0.3",
```
the config
    
```
module.exports = {
  cache: {
    type: 'filesystem',
    cacheDirectory: resolve(
      __dirname,
      `node_modules/.cache/webpack-${process.env.NODE_ENV}`
    ),
  },
  devServer: {
    historyApiFallback: true,
    hot: false,
    host,
    port: 8383,
    static: {
      directory: urlJoin(publicDir, config.url_root),
    },
  },
  devtool: 'eval-source-map',
  entry: {
    application: resolve(__dirname, 'app', 'index.js'),
  },
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.coffee|.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          cacheDirectory: resolve(
            __dirname,
            `node_modules/.cache/babel-loader-${process.env.NODE_ENV}`
          ),
          cacheCompression: false,
        },
      },
      {
        test: /\.coffee$/,
        exclude: /node_modules/,
        loader: 'coffee-loader',
      },
      {
        test: require.resolve('jquery'),
        loader: 'expose-loader',
        options: {
          exposes: ['$', 'jQuery'],
        },
      },
      {
        test: /\.js$/,
        exclude: /node_modules\/mocha/, // because reading maps initializes mocha once, and then the second, real use makes it corrupted
        enforce: 'pre',
        use: ['source-map-loader'],
      },
    ],
  },
  output: {
    filename: 'javascripts/[name].js',
    path: publicDir,
  },
  plugins: _.compact([
    new MiniCssExtractPlugin({
      filename: ifProduction(
        'stylesheets/[name].[contenthash].css',
        'stylesheets/[name].css'
      ),
    }),
    new DebugNamesPlugin()
  ]),
  resolve: {
    extensions: ['.js', '.coffee', '.hbs', '.styl', '.less', '.css', '.svg'],
    modules: [resolve(__dirname, 'app'), 'node_modules'],
    fallback: {buffer: false, fs: false},
  },
  node: {__filename: true}, // is used in unit tests for full file name access
  target: 'web',
}
```    

Not sure if it helps anyway. I guess webpack does not like `false` values for `__webpack_modules__[moduleId]` calls.

**Comment by Trias** [comment]
Can you update to 1.1.1 and clear you cache with `rm -rf node_modules/.cache` and try again?

I updated the plugin for webpack 5, maybe this fixes your issue. If not, please provide a repo which shows the issue.

**Comment by eugenet8k** [comment]
Thank you @Trias, I tried it, and this time it seems it does not do anything to the source code itself, the imports stay ugly:

```
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var chaplin__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! chaplin */ "./node_modules/chaplin/chaplin.js");
/* harmony import */ var chaplin__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(chaplin__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var moment__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! moment */ "./node_modules/moment/moment.js");
/* harmony import */ var moment__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(moment__WEBPACK_IMPORTED_MODULE_2__);
```

This is with the same config, reset cache and with version debug-names-webpack-plugin `v1.1.1`

**Comment by Trias** [comment]
Jep looks like it‘s not doing anything. As i said i can‘t say where the problem is. Either you have to investigate yourself or provide a repo with a reproduction.

**Comment by trias-at-alloy** [comment]
i've refactored the code a bit (and also renamed the plugin to `debug-import-vars-webpack-plugin`). It uses a less invasive approach, it may fix your issue (but speculative of course)

**Comment by eugenet8k** [comment]
Thank you @trias-at-alloy for your updates. I tried the last one and it does change the source code, but it rather looks more complex than before. This is the look of the average React component:

```
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);

let React,useMemo,useEffect,useRef,useReducer,useContext,useCallback;setTimeout(() => {React = react__WEBPACK_IMPORTED_MODULE_0__.default;if(typeof React==="undefined")React=react__WEBPACK_IMPORTED_MODULE_0__;useMemo = react__WEBPACK_IMPORTED_MODULE_0__.useMemo;useEffect = react__WEBPACK_IMPORTED_MODULE_0__.useEffect;useRef = react__WEBPACK_IMPORTED_MODULE_0__.useRef;useReducer = react__WEBPACK_IMPORTED_MODULE_0__.useReducer;useContext = react__WEBPACK_IMPORTED_MODULE_0__.useContext;useCallback = react__WEBPACK_IMPORTED_MODULE_0__.useCallback}, 0);
```

Also, the browser console has a big number of errors like:

```
some-layout.js:25 Uncaught ReferenceError: react_use__WEBPACK_IMPORTED_MODULE_13__ is not defined
    at eval (some-layout.js:25:33)
```

Which seems to be specific to the NPM imports. I assume something about the way how npm package is bundled (with or without default export etc...)

The source code itself does not look like it benefits from all of the above, I still see:

```
const context = (0,react__WEBPACK_IMPORTED_MODULE_0__.useMemo)(() => ({ ...
```

**Comment by Trias** [comment]
No, the source code will be basically stay the same, the plugin will not *replace* the "ugly" names, but instead provide with *additional* names which you can use in your debugger. Together with source maps this should simplify your debugging experience.

What the plugin does is that it adds this line:

```
let React,useMemo,useEffect,useRef,useReducer,useContext,useCallback;setTimeout(() => {React = react__WEBPACK_IMPORTED_MODULE_0__.default;if(typeof React==="undefined")React=react__WEBPACK_IMPORTED_MODULE_0__;useMemo = react__WEBPACK_IMPORTED_MODULE_0__.useMemo;useEffect = react__WEBPACK_IMPORTED_MODULE_0__.useEffect;useRef = react__WEBPACK_IMPORTED_MODULE_0__.useRef;useReducer = react__WEBPACK_IMPORTED_MODULE_0__.useReducer;useContext = react__WEBPACK_IMPORTED_MODULE_0__.useContext;useCallback = react__WEBPACK_IMPORTED_MODULE_0__.useCallback}, 0);
```

which allow you to use the variables in your dev tools. We cannot get rid of `react__WEBPACK_IMPORTED_MODULE_0__` unfortunately because that would break ecmascript compatibility. If you are not using source maps already i recommend you to look it up.

Regarding
```
some-layout.js:25 Uncaught ReferenceError: react_use__WEBPACK_IMPORTED_MODULE_13__ is not defined
    at eval (some-layout.js:25:33)
```

Are you, by any chance importing react twice? Anything else about that import that's interesting? Maybe you could try to reproduce it to a minimal reproduction. The plugin does seem to work as expected for the first code snippet you posted.

**Comment by Trias** [comment]
@eugenet8k could you resolve your issue?

**Comment by eugenet8k** [comment]
@Trias yes, thank you!
